name: Naukri Automation Headless

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 7:00 AM IST
  workflow_dispatch:      # Allows manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver==3.5.5 selenium>=4.10.0

    - name: Run undetected-chromedriver
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python -c "import undetected_chromedriver as uc
options = uc.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
try:
    driver = uc.Chrome(options=options)
    driver.get('https://www.naukri.com/')
    print('✅ Page loaded successfully:', driver.title)
except Exception as e:
    print('❌ Failed to load page:', e)
finally:
    driver.quit()"
